all:
  children:
    app:
      hosts:
        appserver-stage: {}
    db:
      hosts:
        dbserver-stage: {}
    stage:
      hosts:
        appserver-stage:
          ansible_host: 62.84.118.9
          internal_ip: unknown
        dbserver-stage:
          ansible_host: 51.250.12.213
          internal_ip: 10.24.29.9
