$ANSIBLE_VAULT;1.1;AES256
32373436646338313761316532373864303733613136656666663235646134343661323961663464
6237663664643237663237373338653862396665623133640a663263353038663333623863653631
33633066323164663034353863303533306562393061613230373939333136306162343164626333
3961346365333365620a633332396639393831623561356630643965343732666531333838616538
30386330346333336435356130383134396465653132663132373230663430326336353731663537
31626665653263376561313531633537366565303065636531323233326235613464343063366333
37613934306439306431636162366532343037376232613162636632386466386664656137363061
61666663633937353866646466313964646464383138336363616535363132303466666235386535
6465
