all:
  children:
    app:
      hosts:
        appserver-stage: {}
    db:
      hosts:
        dbserver-stage: {}
    stage:
      hosts:
        appserver-stage:
          ansible_host: 158.160.35.78
          internal_ip: unknown
        dbserver-stage:
          ansible_host: 158.160.57.174
          internal_ip: 10.60.172.14
